// Reviewed scenario-level BR expectations for the recorded v1 outcomes.
// Sources: HubRefactoring docs/legacy-baseline/03-business-rules.md and
// docs/renovation/capability-map.md. Keep this independent of scenario tags and the matrix.
export const V1_SCENARIO_BUSINESS_RULES = {
  // GET /v1/player
  "player-query-outbound-error": ["BR-01", "BR-13", "BR-42"],
  "player-query-outbound-success": ["BR-01", "BR-13", "BR-42"],
  "player-query-outbound-timeout": ["BR-01", "BR-13", "BR-42"],
  "player-query-signature-failed": ["BR-01"],
  "player-query-unknown-station": ["BR-01"],
  "player-query-validation-failed": ["BR-01"],
  // GET /v1/player/balance
  "player-balance-no-play-log": ["BR-01"],
  "player-balance-outbound-error": ["BR-01", "BR-42"],
  "player-balance-outbound-success": ["BR-01", "BR-42"],
  "player-balance-outbound-timeout": ["BR-01", "BR-42"],
  "player-balance-signature-failed": ["BR-01"],
  "player-balance-unknown-station": ["BR-01"],
  "player-balance-validation-failed": ["BR-01"],
  // POST /v1/player
  "player-create-account-suffix-error": ["BR-01", "BR-03"],
  "player-create-duplicate-player": ["BR-01", "BR-02", "BR-03"],
  "player-create-existing": ["BR-01", "BR-02", "BR-03"],
  "player-create-fresh": ["BR-01", "BR-02", "BR-03"],
  "player-create-signature-failed": ["BR-01"],
  "player-create-unknown-station": ["BR-01"],
  "player-create-validation-failed": ["BR-01"],
  // POST /v1/wallet/deposit
  "deposit-duplicate-main-wallet": ["BR-01", "BR-10", "BR-11"],
  "deposit-duplicate-trade-no": ["BR-01", "BR-20"],
  "deposit-provider-failure": ["BR-01", "BR-11", "BR-12", "BR-20", "BR-22", "BR-23", "BR-46"],
  "deposit-provider-timeout": ["BR-01", "BR-11", "BR-12", "BR-20", "BR-22", "BR-23", "BR-46"],
  "deposit-queued-sync": ["BR-01", "BR-11", "BR-12", "BR-20", "BR-22", "BR-23", "BR-46"],
  "deposit-signature-failed": ["BR-01"],
  "deposit-success": ["BR-01", "BR-11", "BR-12", "BR-20", "BR-22", "BR-23", "BR-46"],
  "deposit-unknown-station": ["BR-01"],
  "deposit-validation-failed": ["BR-01"],
  // POST /v1/wallet/withdraw
  "withdrawal-duplicate-main-wallet": ["BR-01", "BR-10", "BR-11"],
  "withdrawal-duplicate-trade-no": ["BR-01", "BR-20"],
  "withdrawal-provider-failure": ["BR-01", "BR-11", "BR-20", "BR-22", "BR-45"],
  "withdrawal-provider-timeout": ["BR-01", "BR-11", "BR-20", "BR-22", "BR-45"],
  "withdrawal-signature-failed": ["BR-01"],
  "withdrawal-success": ["BR-01", "BR-11", "BR-20", "BR-22", "BR-45"],
  "withdrawal-unknown-station": ["BR-01"],
  "withdrawal-validation-failed": ["BR-01"],
  "withdrawal-wallet-lock-occupied": ["BR-01", "BR-40"],
  // POST /v1/wallet/check-transaction
  "check-transaction-both-hit": ["BR-01", "BR-26"],
  "check-transaction-deposit-hit": ["BR-01", "BR-26"],
  "check-transaction-duplicate-trade-no": ["BR-01", "BR-21", "BR-26"],
  "check-transaction-not-found": ["BR-01", "BR-26"],
  "check-transaction-signature-failed": ["BR-01"],
  "check-transaction-soft-deleted": ["BR-01", "BR-21", "BR-26"],
  "check-transaction-unknown-station": ["BR-01"],
  "check-transaction-validation-failed": ["BR-01"],
  "check-transaction-withdrawal-hit": ["BR-01", "BR-26"],
  // POST /v1/wallet/check-transaction-for-test
  "check-transaction-for-test-duplicate-trade-no": ["BR-01", "BR-21", "BR-48"],
  "check-transaction-for-test-no-remittance": ["BR-01"],
  "check-transaction-for-test-provider-failed": ["BR-01", "BR-48"],
  "check-transaction-for-test-provider-timeout": ["BR-01", "BR-48"],
  "check-transaction-for-test-signature-failed": ["BR-01"],
  "check-transaction-for-test-success": ["BR-01", "BR-48"],
  "check-transaction-for-test-unknown-station": ["BR-01"],
  "check-transaction-for-test-validation-failed": ["BR-01"],
  "check-transaction-for-test-withdrawal-success": ["BR-01", "BR-48"],
  "check-transaction-for-test-wrong-account": ["BR-01"],
  // POST /v1/wallet/balance-difference
  "balance-difference-consistent": ["BR-01", "BR-35"],
  "balance-difference-inconsistent": ["BR-01", "BR-35"],
  "balance-difference-no-game-wallet": ["BR-01"],
  "balance-difference-no-play-log": ["BR-01"],
  "balance-difference-pending-transfer": ["BR-01", "BR-35"],
  "balance-difference-provider-failed": ["BR-01", "BR-35"],
  "balance-difference-provider-timeout": ["BR-01", "BR-35"],
  "balance-difference-signature-failed": ["BR-01"],
  "balance-difference-unknown-station": ["BR-01"],
  "balance-difference-validation-failed": ["BR-01"],
  // GET /v1/games
  "catalog-games-maintenance": ["BR-01", "BR-70", "BR-71", "BR-53"],
  "catalog-games-no-active-companies": ["BR-01", "BR-70", "BR-72"],
  "catalog-games-orphan-company": ["BR-01", "BR-70"],
  "catalog-games-redis-maintenance": ["BR-01", "BR-70", "BR-71", "BR-53"],
  "catalog-games-signature-failed": ["BR-01"],
  "catalog-games-success": ["BR-01", "BR-70"],
  "catalog-games-unknown-station": ["BR-01"],
  "catalog-games-validation": ["BR-01"],
  // GET /v1/games/types
  "catalog-types-inactive": ["BR-01"],
  "catalog-types-signature-failed": ["BR-01"],
  "catalog-types-success": ["BR-01"],
  "catalog-types-unknown-station": ["BR-01"],
  "catalog-types-validation": ["BR-01"],
  // GET /v1/games/companies
  "catalog-companies-game-type-populated": ["BR-01"],
  "catalog-companies-maintenance": ["BR-01"],
  "catalog-companies-orphan-company": ["BR-01"],
  "catalog-companies-redis-maintenance": ["BR-01"],
  "catalog-companies-signature-failed": ["BR-01"],
  "catalog-companies-success": ["BR-01"],
  "catalog-companies-unknown-station": ["BR-01"],
  "catalog-companies-validation": ["BR-01"],
  // POST /v1/games/launch
  "pg-callback-auth-rejected": ["BR-01", "BR-50", "BR-57", "BR-58", "BR-80"],
  "pg-callback-expired": ["BR-01", "BR-50", "BR-57", "BR-58", "BR-80"],
  "pg-callback-wrong-ops": ["BR-01", "BR-50", "BR-57", "BR-58", "BR-80"],
  "pg-launch-callback": ["BR-01", "BR-50", "BR-57", "BR-58", "BR-80"],
  "pg-launch-maintenance": ["BR-01", "BR-50", "BR-53", "BR-54"],
  "pg-launch-missing-game": ["BR-01", "BR-50", "BR-56"],
  "pg-launch-provider-failure": ["BR-01", "BR-50", "BR-56", "BR-57"],
  "pg-launch-recall-failure": ["BR-01", "BR-50", "BR-57", "BR-58", "BR-80", "BR-40", "BR-41", "BR-42", "BR-43"],
  "pg-launch-recall": ["BR-01", "BR-50", "BR-57", "BR-58", "BR-80", "BR-40", "BR-41", "BR-42", "BR-44"],
  // GET /v1/currencies
  "currency-index-inactive-station-currency": ["BR-01"],
  "currency-index-signature-failed": ["BR-01"],
  "currency-index-unknown-station": ["BR-01"],
  "currency-index-validation": ["BR-01"],
  "currency-index": ["BR-01"],
  // GET /v1/currencies/exchange-rate
  "currency-exchange-rate-list-signature-failed": ["BR-01"],
  "currency-exchange-rate-list-unknown-station": ["BR-01"],
  "currency-exchange-rate-list-validation": ["BR-01"],
  "currency-exchange-rate-list": ["BR-01", "BR-92"],
  // GET /v1/currencies/exchange-rate/{currency}
  "currency-exchange-rate-show-inactive-currency": ["BR-01", "BR-92"],
  "currency-exchange-rate-show-signature-failed": ["BR-01"],
  "currency-exchange-rate-show-unknown-currency": ["BR-01", "BR-92"],
  "currency-exchange-rate-show-unknown-station": ["BR-01"],
  "currency-exchange-rate-show-validation": ["BR-01"],
  "currency-exchange-rate-show": ["BR-01", "BR-92"],
  // GET /v1/sms
  "sms-index-signature-failed": ["BR-01"],
  "sms-index-unknown-station": ["BR-01"],
  "sms-index-validation": ["BR-01"],
  "sms-index": ["BR-01"],
  // POST /v1/sms
  "sms-update-invalid-settings": ["BR-01"],
  "sms-update-mass-assignment": ["BR-01"],
  "sms-update-signature-failed": ["BR-01"],
  "sms-update-unknown-station": ["BR-01"],
  "sms-update-validation": ["BR-01"],
  // POST /v1/sms/send
  "sms-send-asmsc-sender-id": ["BR-01", "BR-90"],
  "sms-send-empty-balance": ["BR-01", "BR-90"],
  "sms-send-inactive": ["BR-01", "BR-90"],
  "sms-send-locked": ["BR-01", "BR-90"],
  "sms-send-signature-failed": ["BR-01"],
  "sms-send-unknown-station": ["BR-01"],
  "sms-send-validation": ["BR-01"],
  "sms-send-without-currency": ["BR-01"],
  // POST /v1/sms/amount
  "sms-amount-abo-send-provider-failure": ["BR-01"],
  "sms-amount-abo-send-success": ["BR-01"],
  "sms-amount-asmsc-provider-failure": ["BR-01"],
  "sms-amount-asmsc-success": ["BR-01"],
  "sms-amount-provider-failure": ["BR-01"],
  "sms-amount-signature-failed": ["BR-01"],
  "sms-amount-success": ["BR-01"],
  "sms-amount-unknown-station": ["BR-01"],
  "sms-amount-validation": ["BR-01"],
  // GET /v1/server/status
  "server-status-unknown-station": [],
  "server-status-unvalidated-params": [],
  "server-status": [],
} as const satisfies Record<string, readonly string[]>;
