FROM alpine:3.21

RUN apk add --no-cache \
    curl \
    git \
    bash \
    mariadb-client \
    php83 \
    php83-cli \
    php83-pdo \
    php83-pdo_mysql \
    php83-pecl-redis \
    php83-pecl-mongodb \
    php83-bcmath \
    php83-mbstring \
    php83-openssl \
    php83-tokenizer \
    php83-xml \
    php83-dom \
    php83-curl \
    php83-fileinfo \
    php83-session \
  && ln -sf /usr/bin/php83 /usr/bin/php

WORKDIR /var/www/html

EXPOSE 8080

CMD ["php", "-S", "0.0.0.0:8080", "public/index.php"]
